/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as MyRequestsRouteImport } from './routes/my-requests'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as GuidedRouteImport } from './routes/guided'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesCategoryRouteImport } from './routes/services.$category'
import { Route as RequestNewRouteImport } from './routes/request.new'
import { Route as RequestLeadIdRouteImport } from './routes/request.$leadId'
import { Route as ProviderWalletRouteImport } from './routes/provider.wallet'
import { Route as ProviderReviewsRouteImport } from './routes/provider.reviews'
import { Route as ProviderOnboardingRouteImport } from './routes/provider.onboarding'
import { Route as ProviderLeadsRouteImport } from './routes/provider.leads'
import { Route as ProviderDashboardRouteImport } from './routes/provider.dashboard'
import { Route as ProviderCalendarRouteImport } from './routes/provider.calendar'
import { Route as PProviderIdRouteImport } from './routes/p.$providerId'
import { Route as CustomerReviewsRouteImport } from './routes/customer.reviews'
import { Route as AuthConfirmRouteImport } from './routes/auth.confirm'
import { Route as ApiPublicAuthEmailHookRouteImport } from './routes/api/public/auth-email-hook'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRequestsRoute = MyRequestsRouteImport.update({
  id: '/my-requests',
  path: '/my-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidedRoute = GuidedRouteImport.update({
  id: '/guided',
  path: '/guided',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCategoryRoute = ServicesCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => ServicesRoute,
} as any)
const RequestNewRoute = RequestNewRouteImport.update({
  id: '/request/new',
  path: '/request/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestLeadIdRoute = RequestLeadIdRouteImport.update({
  id: '/request/$leadId',
  path: '/request/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderWalletRoute = ProviderWalletRouteImport.update({
  id: '/provider/wallet',
  path: '/provider/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderReviewsRoute = ProviderReviewsRouteImport.update({
  id: '/provider/reviews',
  path: '/provider/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderOnboardingRoute = ProviderOnboardingRouteImport.update({
  id: '/provider/onboarding',
  path: '/provider/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderLeadsRoute = ProviderLeadsRouteImport.update({
  id: '/provider/leads',
  path: '/provider/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderDashboardRoute = ProviderDashboardRouteImport.update({
  id: '/provider/dashboard',
  path: '/provider/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderCalendarRoute = ProviderCalendarRouteImport.update({
  id: '/provider/calendar',
  path: '/provider/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const PProviderIdRoute = PProviderIdRouteImport.update({
  id: '/p/$providerId',
  path: '/p/$providerId',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerReviewsRoute = CustomerReviewsRouteImport.update({
  id: '/customer/reviews',
  path: '/customer/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthEmailHookRoute = ApiPublicAuthEmailHookRouteImport.update({
  id: '/api/public/auth-email-hook',
  path: '/api/public/auth-email-hook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/guided': typeof GuidedRoute
  '/messages': typeof MessagesRoute
  '/my-requests': typeof MyRequestsRoute
  '/providers': typeof ProvidersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/customer/reviews': typeof CustomerReviewsRoute
  '/p/$providerId': typeof PProviderIdRoute
  '/provider/calendar': typeof ProviderCalendarRoute
  '/provider/dashboard': typeof ProviderDashboardRoute
  '/provider/leads': typeof ProviderLeadsRoute
  '/provider/onboarding': typeof ProviderOnboardingRoute
  '/provider/reviews': typeof ProviderReviewsRoute
  '/provider/wallet': typeof ProviderWalletRoute
  '/request/$leadId': typeof RequestLeadIdRoute
  '/request/new': typeof RequestNewRoute
  '/services/$category': typeof ServicesCategoryRoute
  '/api/public/auth-email-hook': typeof ApiPublicAuthEmailHookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/guided': typeof GuidedRoute
  '/messages': typeof MessagesRoute
  '/my-requests': typeof MyRequestsRoute
  '/providers': typeof ProvidersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/customer/reviews': typeof CustomerReviewsRoute
  '/p/$providerId': typeof PProviderIdRoute
  '/provider/calendar': typeof ProviderCalendarRoute
  '/provider/dashboard': typeof ProviderDashboardRoute
  '/provider/leads': typeof ProviderLeadsRoute
  '/provider/onboarding': typeof ProviderOnboardingRoute
  '/provider/reviews': typeof ProviderReviewsRoute
  '/provider/wallet': typeof ProviderWalletRoute
  '/request/$leadId': typeof RequestLeadIdRoute
  '/request/new': typeof RequestNewRoute
  '/services/$category': typeof ServicesCategoryRoute
  '/api/public/auth-email-hook': typeof ApiPublicAuthEmailHookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/guided': typeof GuidedRoute
  '/messages': typeof MessagesRoute
  '/my-requests': typeof MyRequestsRoute
  '/providers': typeof ProvidersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/customer/reviews': typeof CustomerReviewsRoute
  '/p/$providerId': typeof PProviderIdRoute
  '/provider/calendar': typeof ProviderCalendarRoute
  '/provider/dashboard': typeof ProviderDashboardRoute
  '/provider/leads': typeof ProviderLeadsRoute
  '/provider/onboarding': typeof ProviderOnboardingRoute
  '/provider/reviews': typeof ProviderReviewsRoute
  '/provider/wallet': typeof ProviderWalletRoute
  '/request/$leadId': typeof RequestLeadIdRoute
  '/request/new': typeof RequestNewRoute
  '/services/$category': typeof ServicesCategoryRoute
  '/api/public/auth-email-hook': typeof ApiPublicAuthEmailHookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/guided'
    | '/messages'
    | '/my-requests'
    | '/providers'
    | '/reset-password'
    | '/services'
    | '/signin'
    | '/signup'
    | '/auth/confirm'
    | '/customer/reviews'
    | '/p/$providerId'
    | '/provider/calendar'
    | '/provider/dashboard'
    | '/provider/leads'
    | '/provider/onboarding'
    | '/provider/reviews'
    | '/provider/wallet'
    | '/request/$leadId'
    | '/request/new'
    | '/services/$category'
    | '/api/public/auth-email-hook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/guided'
    | '/messages'
    | '/my-requests'
    | '/providers'
    | '/reset-password'
    | '/services'
    | '/signin'
    | '/signup'
    | '/auth/confirm'
    | '/customer/reviews'
    | '/p/$providerId'
    | '/provider/calendar'
    | '/provider/dashboard'
    | '/provider/leads'
    | '/provider/onboarding'
    | '/provider/reviews'
    | '/provider/wallet'
    | '/request/$leadId'
    | '/request/new'
    | '/services/$category'
    | '/api/public/auth-email-hook'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/guided'
    | '/messages'
    | '/my-requests'
    | '/providers'
    | '/reset-password'
    | '/services'
    | '/signin'
    | '/signup'
    | '/auth/confirm'
    | '/customer/reviews'
    | '/p/$providerId'
    | '/provider/calendar'
    | '/provider/dashboard'
    | '/provider/leads'
    | '/provider/onboarding'
    | '/provider/reviews'
    | '/provider/wallet'
    | '/request/$leadId'
    | '/request/new'
    | '/services/$category'
    | '/api/public/auth-email-hook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  GuidedRoute: typeof GuidedRoute
  MessagesRoute: typeof MessagesRoute
  MyRequestsRoute: typeof MyRequestsRoute
  ProvidersRoute: typeof ProvidersRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
  CustomerReviewsRoute: typeof CustomerReviewsRoute
  PProviderIdRoute: typeof PProviderIdRoute
  ProviderCalendarRoute: typeof ProviderCalendarRoute
  ProviderDashboardRoute: typeof ProviderDashboardRoute
  ProviderLeadsRoute: typeof ProviderLeadsRoute
  ProviderOnboardingRoute: typeof ProviderOnboardingRoute
  ProviderReviewsRoute: typeof ProviderReviewsRoute
  ProviderWalletRoute: typeof ProviderWalletRoute
  RequestLeadIdRoute: typeof RequestLeadIdRoute
  RequestNewRoute: typeof RequestNewRoute
  ApiPublicAuthEmailHookRoute: typeof ApiPublicAuthEmailHookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-requests': {
      id: '/my-requests'
      path: '/my-requests'
      fullPath: '/my-requests'
      preLoaderRoute: typeof MyRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guided': {
      id: '/guided'
      path: '/guided'
      fullPath: '/guided'
      preLoaderRoute: typeof GuidedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$category': {
      id: '/services/$category'
      path: '/$category'
      fullPath: '/services/$category'
      preLoaderRoute: typeof ServicesCategoryRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/request/new': {
      id: '/request/new'
      path: '/request/new'
      fullPath: '/request/new'
      preLoaderRoute: typeof RequestNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request/$leadId': {
      id: '/request/$leadId'
      path: '/request/$leadId'
      fullPath: '/request/$leadId'
      preLoaderRoute: typeof RequestLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/wallet': {
      id: '/provider/wallet'
      path: '/provider/wallet'
      fullPath: '/provider/wallet'
      preLoaderRoute: typeof ProviderWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/reviews': {
      id: '/provider/reviews'
      path: '/provider/reviews'
      fullPath: '/provider/reviews'
      preLoaderRoute: typeof ProviderReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/onboarding': {
      id: '/provider/onboarding'
      path: '/provider/onboarding'
      fullPath: '/provider/onboarding'
      preLoaderRoute: typeof ProviderOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/leads': {
      id: '/provider/leads'
      path: '/provider/leads'
      fullPath: '/provider/leads'
      preLoaderRoute: typeof ProviderLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/dashboard': {
      id: '/provider/dashboard'
      path: '/provider/dashboard'
      fullPath: '/provider/dashboard'
      preLoaderRoute: typeof ProviderDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/calendar': {
      id: '/provider/calendar'
      path: '/provider/calendar'
      fullPath: '/provider/calendar'
      preLoaderRoute: typeof ProviderCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$providerId': {
      id: '/p/$providerId'
      path: '/p/$providerId'
      fullPath: '/p/$providerId'
      preLoaderRoute: typeof PProviderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/reviews': {
      id: '/customer/reviews'
      path: '/customer/reviews'
      fullPath: '/customer/reviews'
      preLoaderRoute: typeof CustomerReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth-email-hook': {
      id: '/api/public/auth-email-hook'
      path: '/api/public/auth-email-hook'
      fullPath: '/api/public/auth-email-hook'
      preLoaderRoute: typeof ApiPublicAuthEmailHookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ServicesRouteChildren {
  ServicesCategoryRoute: typeof ServicesCategoryRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesCategoryRoute: ServicesCategoryRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  GuidedRoute: GuidedRoute,
  MessagesRoute: MessagesRoute,
  MyRequestsRoute: MyRequestsRoute,
  ProvidersRoute: ProvidersRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  AuthConfirmRoute: AuthConfirmRoute,
  CustomerReviewsRoute: CustomerReviewsRoute,
  PProviderIdRoute: PProviderIdRoute,
  ProviderCalendarRoute: ProviderCalendarRoute,
  ProviderDashboardRoute: ProviderDashboardRoute,
  ProviderLeadsRoute: ProviderLeadsRoute,
  ProviderOnboardingRoute: ProviderOnboardingRoute,
  ProviderReviewsRoute: ProviderReviewsRoute,
  ProviderWalletRoute: ProviderWalletRoute,
  RequestLeadIdRoute: RequestLeadIdRoute,
  RequestNewRoute: RequestNewRoute,
  ApiPublicAuthEmailHookRoute: ApiPublicAuthEmailHookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
