/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as PostJobRouteImport } from './routes/post-job'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesCategoryRouteImport } from './routes/services.$category'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const PostJobRoute = PostJobRouteImport.update({
  id: '/post-job',
  path: '/post-job',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCategoryRoute = ServicesCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/post-job': typeof PostJobRoute
  '/providers': typeof ProvidersRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/$category': typeof ServicesCategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/post-job': typeof PostJobRoute
  '/providers': typeof ProvidersRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/$category': typeof ServicesCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/post-job': typeof PostJobRoute
  '/providers': typeof ProvidersRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/$category': typeof ServicesCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/post-job'
    | '/providers'
    | '/services'
    | '/services/$category'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/post-job' | '/providers' | '/services' | '/services/$category'
  id:
    | '__root__'
    | '/'
    | '/post-job'
    | '/providers'
    | '/services'
    | '/services/$category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PostJobRoute: typeof PostJobRoute
  ProvidersRoute: typeof ProvidersRoute
  ServicesRoute: typeof ServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-job': {
      id: '/post-job'
      path: '/post-job'
      fullPath: '/post-job'
      preLoaderRoute: typeof PostJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$category': {
      id: '/services/$category'
      path: '/$category'
      fullPath: '/services/$category'
      preLoaderRoute: typeof ServicesCategoryRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesCategoryRoute: typeof ServicesCategoryRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesCategoryRoute: ServicesCategoryRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PostJobRoute: PostJobRoute,
  ProvidersRoute: ProvidersRoute,
  ServicesRoute: ServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
