/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as PostJobRouteImport } from './routes/post-job'
import { Route as MyJobsRouteImport } from './routes/my-jobs'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesCategoryRouteImport } from './routes/services.$category'
import { Route as ProviderOnboardingRouteImport } from './routes/provider.onboarding'
import { Route as ProviderDashboardRouteImport } from './routes/provider.dashboard'
import { Route as PProviderIdRouteImport } from './routes/p.$providerId'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const PostJobRoute = PostJobRouteImport.update({
  id: '/post-job',
  path: '/post-job',
  getParentRoute: () => rootRouteImport,
} as any)
const MyJobsRoute = MyJobsRouteImport.update({
  id: '/my-jobs',
  path: '/my-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCategoryRoute = ServicesCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => ServicesRoute,
} as any)
const ProviderOnboardingRoute = ProviderOnboardingRouteImport.update({
  id: '/provider/onboarding',
  path: '/provider/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderDashboardRoute = ProviderDashboardRouteImport.update({
  id: '/provider/dashboard',
  path: '/provider/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PProviderIdRoute = PProviderIdRouteImport.update({
  id: '/p/$providerId',
  path: '/p/$providerId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/my-jobs': typeof MyJobsRoute
  '/post-job': typeof PostJobRoute
  '/providers': typeof ProvidersRoute
  '/services': typeof ServicesRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/p/$providerId': typeof PProviderIdRoute
  '/provider/dashboard': typeof ProviderDashboardRoute
  '/provider/onboarding': typeof ProviderOnboardingRoute
  '/services/$category': typeof ServicesCategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/my-jobs': typeof MyJobsRoute
  '/post-job': typeof PostJobRoute
  '/providers': typeof ProvidersRoute
  '/services': typeof ServicesRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/p/$providerId': typeof PProviderIdRoute
  '/provider/dashboard': typeof ProviderDashboardRoute
  '/provider/onboarding': typeof ProviderOnboardingRoute
  '/services/$category': typeof ServicesCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/my-jobs': typeof MyJobsRoute
  '/post-job': typeof PostJobRoute
  '/providers': typeof ProvidersRoute
  '/services': typeof ServicesRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/p/$providerId': typeof PProviderIdRoute
  '/provider/dashboard': typeof ProviderDashboardRoute
  '/provider/onboarding': typeof ProviderOnboardingRoute
  '/services/$category': typeof ServicesCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/my-jobs'
    | '/post-job'
    | '/providers'
    | '/services'
    | '/signin'
    | '/signup'
    | '/jobs/$jobId'
    | '/p/$providerId'
    | '/provider/dashboard'
    | '/provider/onboarding'
    | '/services/$category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/my-jobs'
    | '/post-job'
    | '/providers'
    | '/services'
    | '/signin'
    | '/signup'
    | '/jobs/$jobId'
    | '/p/$providerId'
    | '/provider/dashboard'
    | '/provider/onboarding'
    | '/services/$category'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/my-jobs'
    | '/post-job'
    | '/providers'
    | '/services'
    | '/signin'
    | '/signup'
    | '/jobs/$jobId'
    | '/p/$providerId'
    | '/provider/dashboard'
    | '/provider/onboarding'
    | '/services/$category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  MyJobsRoute: typeof MyJobsRoute
  PostJobRoute: typeof PostJobRoute
  ProvidersRoute: typeof ProvidersRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  PProviderIdRoute: typeof PProviderIdRoute
  ProviderDashboardRoute: typeof ProviderDashboardRoute
  ProviderOnboardingRoute: typeof ProviderOnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-job': {
      id: '/post-job'
      path: '/post-job'
      fullPath: '/post-job'
      preLoaderRoute: typeof PostJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-jobs': {
      id: '/my-jobs'
      path: '/my-jobs'
      fullPath: '/my-jobs'
      preLoaderRoute: typeof MyJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$category': {
      id: '/services/$category'
      path: '/$category'
      fullPath: '/services/$category'
      preLoaderRoute: typeof ServicesCategoryRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/provider/onboarding': {
      id: '/provider/onboarding'
      path: '/provider/onboarding'
      fullPath: '/provider/onboarding'
      preLoaderRoute: typeof ProviderOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/dashboard': {
      id: '/provider/dashboard'
      path: '/provider/dashboard'
      fullPath: '/provider/dashboard'
      preLoaderRoute: typeof ProviderDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$providerId': {
      id: '/p/$providerId'
      path: '/p/$providerId'
      fullPath: '/p/$providerId'
      preLoaderRoute: typeof PProviderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ServicesRouteChildren {
  ServicesCategoryRoute: typeof ServicesCategoryRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesCategoryRoute: ServicesCategoryRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  MyJobsRoute: MyJobsRoute,
  PostJobRoute: PostJobRoute,
  ProvidersRoute: ProvidersRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  PProviderIdRoute: PProviderIdRoute,
  ProviderDashboardRoute: ProviderDashboardRoute,
  ProviderOnboardingRoute: ProviderOnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
